# 
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: scenarios-100-tf14

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  TF_CLI_ARGS: '-no-color'
  TF_CLI_ARGS_destroy: '-auto-approve -refresh=false'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ROVER_RUNNER: true

jobs:
  foundations:
    name: foundations
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
          region: ["southeastasia"]
          random_length: ['5']

    container:
      image: aztfmod/rover:0.14.7-2103.0105
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: Azure/caf-terraform-landingzones
          path: public
          ref: '2102.0.0'

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"

      - name: launchpad
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/public/landingzones/caf_launchpad -a apply \
            -var-folder ${GITHUB_WORKSPACE}/public/landingzones/caf_launchpad/scenario/100 \
            -level level0 \
            -launchpad \
            -parallelism=30 \
            --environment ${{ github.run_id }} \
            '-var random_length=${{ matrix.random_length }}' \
            '-var prefix=g${{ github.run_id }}' \
            '-var regions={region1="${{ matrix.region }}"}' \
            '-var tags={environment="${{ github.run_id }}"}'


  examples:
    name: examples
    runs-on: ubuntu-latest

    needs: foundations

    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
          config_files: [
            "app_gateway/100-simple-app-gateway",
            "app_insights/100-all-attributes",
            "app_insights/100-simple",
            "automation/100-simple-automation-account",
            "azure_ad/102-password-rotation",
            "compute/availability_set/100-simple-availabilityset",
            "compute/availability_set/101-availabilityset-with-proximity-placement-group",
            "compute/container_groups/101-aci-rover",
            "compute/container_registry/100-simple-acr",
            "compute/kubernetes_services/101-single-cluster",
            "compute/proximity_placement_group",
            "compute/virtual_machine/100-single-linux-vm",
            "compute/virtual_machine/101-single-windows-vm",
            "compute/virtual_machine/104-single-windows-backup",
            "compute/virtual_machine/211-vm-bastion-winrm-agents",
            "cosmos_db/100-simple-cosmos-db-cassandra",
            "cosmos_db/100-simple-cosmos-db-gremlin",
            "cosmos_db/100-simple-cosmos-db-mongo",
            "cosmos_db/100-simple-cosmos-db-sql",
            "cosmos_db/100-simple-cosmos-db-table",
            "databricks/100-simple-databricks",
            "datalake/101-datalake-storage",
            "eventhub/100-simple-eventhub-namespace",
            "eventhub/101-evh-namespace-with-private-endpoint",
            "eventhub/102-namespace-and-evh-with-auth-rules",
            "eventhub/103-eventhub-consumer-groups",
            "keyvault/102-keyvault-cert-issuer",
            "machine_learning/100-aml",
            "machine_learning/101-aml-vnet",
            "mariadb_server/100-simple-mariadb",
            "mariadb_server/101-vnet-rule-mariadb",
            "mariadb_server/102-private-endpoint-mariadb",
            "mariadb_server/103-private-endpoint-with-fw-rule-mariadb",
            "monitoring/100-service-health-alerts",
            "mssql_server/101-sqlserver-simple",
            "mssql_server/102-sqlserver-extend",
            "mssql_server/104-sqlserver-elastic_pools",
            "mssql_server/105-sqlserver-failover_groups",
            "mysql_server/100-simple-mysql",
            "mysql_server/101-vnet-rule-mysql",
            "mysql_server/102-private-endpoint-mysql",
            "mysql_server/103-private-endpoint-with-fw-rule-mysql",
            "netapp/101-nfs",
            "networking/dns_zones/100-simple-dns_zone",
            "networking/domain_name_registrations/100-register-domain-default_domain_registrar_dns",
            "networking/front_door/100-simple-front_door",
            "networking/front_door/101-front_door_waf",
            "networking/ip_group/100-simple-ip_group",
            "networking/ip_group/101-firewall-ip_group",
            "networking/load_balancers/100-simple-load-balancer-basic-sku",
            "networking/load_balancers/101-load-balancer-with-rules",
            "networking/load_balancers/102-internal-load-balancer",
            "networking/private_dns/100-private-dns-vnet-links",
            "networking/private_links/endpoints/centralized",
            "networking/virtual_network_gateway/103-vpn-site-to-site-connection",
            "networking/virtual_network/100-subnet-delegation",
            "networking/virtual_network/101-vnet-peering-nsg",
            "networking/virtual_wan/100-vwan-multi-hubs",
            "networking/virtual_wan/101-vwan-multi-hubs-firewalls",
            "postgresql_server/100-simple-postgresql",
            "postgresql_server/101-vnet-rule-postgresql",
            "postgresql_server/102-private-endpoint-postgresql",
            "postgresql_server/103-private-endpoint-with-fw-rule",
            "recovery_vault/101-simple-asrv",
            "recovery_vault/102-asr-protection",
            "recovery_vault/103-asr-with-private-endpoint",
            "redis_cache/100-redis-standard",
            "synapse_analytics/100-synapse",
            "synapse_analytics/101-synapse-sparkpool",
            "webapps/appservice/101-appservice-simple",
            "webapps/appservice/102-appservice-slots",
            "webapps/appservice/103-appservice-extend",
            "webapps/appservice/104-appservice-appinsight",
            "webapps/appservice/105-appservice-backup"
            # "networking/virtual_wan/102-vwan-multi-hubs-gw",
          ]

    container:
      image: aztfmod/rover:0.14.7-2103.0105
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: deploy example
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/examples -a apply \
            -level level1 \
            -tfstate $(basename ${{ matrix.config_files }}).tfstate \
            -var-folder ${GITHUB_WORKSPACE}/examples/${{ matrix.config_files }} \
            -var var_folder_path="${GITHUB_WORKSPACE}/examples/${{ matrix.config_files }}" \
            --environment ${{ github.run_id }} \
            '-var tags={environment="${{ github.run_id }}"}'

      - name: destroy example
        if: always()
        run: |
          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/examples -a destroy \
            -level level1 \
            -tfstate $(basename ${{ matrix.config_files }}).tfstate \
            -var-folder ${GITHUB_WORKSPACE}/examples/${{ matrix.config_files }} \
            -var var_folder_path="${GITHUB_WORKSPACE}/examples/${{ matrix.config_files }}" \
            --environment ${{ github.run_id }} \
            -auto-approve


  foundations_destroy:
    name: foundations_destroy
    runs-on: ubuntu-latest
    if: always()
    needs: examples

    strategy:
      fail-fast: false
      matrix:
          region: ["southeastasia"]

    container:
      image: aztfmod/rover:0.14.7-2103.0105
      options: --user 0

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Azure/caf-terraform-landingzones
          path: public
          ref: '2102.0.0'

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"

      - name: Remove launchpad
        run: |

          /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/public/landingzones/caf_launchpad/ -a destroy \
            -level level0 \
            -var-folder ${GITHUB_WORKSPACE}/public/landingzones/caf_launchpad/scenario/100 \
            -launchpad \
            --environment ${{ github.run_id }} \
            -parallelism=30 \
            '-var prefix=g${{ github.run_id }}' \
            '-var regions={region1="${{ matrix.region }}"}' \
            '-var tags={environment="${{ github.run_id }}"}' \
            -auto-approve


      - name: Complete purge
        if: ${{ always() }}
        run: |
          for i in `az monitor diagnostic-settings subscription list -o tsv --query "value[?contains(name, '${{ github.run_id }}' )].name"`; do echo "purging subscription diagnostic-settings: $i" && $(az monitor diagnostic-settings subscription delete --name $i --yes); done
          for i in `az monitor log-profiles list -o tsv --query '[].name'`; do az monitor log-profiles delete --name $i; done
          for i in `az ad group list --query "[?contains(displayName, '${{ github.run_id }}')].objectId" -o tsv`; do echo "purging Azure AD group: $i" && $(az ad group delete --verbose --group $i || true); done
          for i in `az ad app list --query "[?contains(displayName, '${{ github.run_id }}')].appId" -o tsv`; do echo "purging Azure AD app: $i" && $(az ad app delete --verbose --id $i || true); done
          for i in `az keyvault list-deleted --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do az keyvault purge --name $i; done
          for i in `az group list --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do echo "purging resource group: $i" && $(az group delete -n $i -y --no-wait || true); done
          for i in `az role assignment list --query "[?contains(roleDefinitionName, '${{ github.run_id }}')].roleDefinitionName" -o tsv`; do echo "purging role assignment: $i" && $(az role assignment delete --role $i || true); done
          for i in `az role definition list --query "[?contains(roleName, '${{ github.run_id }}')].roleName" -o tsv`; do echo "purging custom role definition: $i" && $(az role definition delete --name $i || true); done
